name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Naturalclar/issue-action@v1.0.0
    - uses: actions/first-interaction@v1.0.0
      with:
        # Github token
        repo-token: "${{secrets.GITHUB_TOKEN}}"
        keywords: ''
        labels: '["HELLO"]'
        pr-message: '["YO A MESSAGE"]'
