name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Issue Labeler
    - uses: Naturalclar/issue-action@v1.0.0
      with:
        # Github token
        github-token: "${{secrets.GITHUB_TOKEN}}"
        # keywords to look for in the issue
        keywords: ''
        # assignees to be assigned when keyword is found
        # labels to be set when keyword is found
        labels: '["HELLO"]'
